apiVersion: v1
kind: Service
metadata:
  name: converter-service
  labels:
    app: converter
spec:
  selector:
    app: converter
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: NodePort
