name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Задача для установки зависимостей
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.3'
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build main.go
        
  # Задача для тестирования
  test:
    runs-on: ubuntu-latest
    needs: install  # Выполняется после установки зависимостей
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.3'
          cache: true
        
      - name: Test with Go
        run: go test -json > TestResults-1.23.3.json
      
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-1.23.3
          path: TestResults-1.23.3.json
