name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Задача для установки зависимостей
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.3'
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build main.go
        
  # Задача для тестирования
  test:
    runs-on: ubuntu-latest
    needs: install  # Выполняется после установки зависимостей
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.3'
          cache: true
        
      - name: Test with Go
        run: go test -json > TestResults-1.23.3.json
      
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-1.23.3
          path: TestResults-1.23.3.json
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    steps:
      - name: Execute ssh command via using private key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd html-converter
            git pull
            docker build -t go_conv .
            docker stop $(docker ps | grep main | awk {'print $1'}) 2> /dev/null
            docker run -p 8082:8082 --restart unless-stopped -d go_conv 
    